runtime: python39
entrypoint: cd ./app && gunicorn -b :$PORT  my_blog_site.wsgi:application

instance_class: F2

env_variables:
  PYTHONPATH: "$PYTHONPATH:/app"
  APPENGINE_URL: https://firstblog-407904.uc.r.appspot.com

handlers:
  - url: /static/
    static_dir: app/staticfiles
  - url: /.*
    script: auto
  
