runtime: python39
entrypoint: cd ./app && gunicorn -b :$PORT  my_blog_site.wsgi:application

instance_class: F2

env_variables:
  PYTHONPATH: "$PYTHONPATH:/app"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto