version: "3"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py create_super_user &&
             python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog_site
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
