# Generated by Django 4.2.7 on 2023-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
