# Generated by Django 4.2.7 on 2023-12-01 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='posted_time',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
