# Generated by Django 4.2.9 on 2024-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
